version: "3.9"

services:
  tiktok-feed:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: karma-8
    ports:
      - "3000:3000"
      - "5500:5500"
    command: ["npm", "run", "reels"]
